on: pull_request

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Lint
        run: yarn lint
      - name: Format
        run: yarn format
